//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MunkaIdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Time = new HashSet<Time>();
        }
    
        public int UserId { get; set; }
        public string Nev { get; set; }
    
        public virtual ICollection<Time> Time { get; set; }
    }
}
